/* Practice activities: independent of the molecular simulation state. */
(()=>{
const $=id=>document.getElementById(id),source='ATGCCA',expected='TACGGT';
for(const [i,base]of [...source].entries()){const label=document.createElement('label');label.textContent=base+' ↓';const select=document.createElement('select');select.setAttribute('aria-label','Complemento de la base '+(i+1)+' ('+base+')');for(const value of ['', 'A','T','C','G']){const option=document.createElement('option');option.value=value;option.textContent=value||'—';select.append(option);}label.append(select);$('complement-inputs').append(label);}
$('complement-form').onsubmit=e=>{e.preventDefault();const inputs=[...$('complement-inputs').querySelectorAll('select')],answer=inputs.map(x=>x.value).join('');inputs.forEach((x,i)=>x.setAttribute('aria-invalid',String(x.value!==expected[i])));$('complement-feedback').textContent=answer===expected?'Correcto. A se une con T y C se une con G':inputs.some(x=>!x.value)?'Completa las seis bases. Pista: A se une con T.':'Todavía no. Puedes volver a intentar. Pista: A ↔ T y C ↔ G; revisa las casillas marcadas.';};
$('complement-reset').onclick=()=>{$('complement-form').reset();$('complement-feedback').textContent='';$('complement-inputs').querySelectorAll('select').forEach(x=>x.removeAttribute('aria-invalid'));};
const questions=[['¿Qué función cumple el ARNm?',['Llevar una copia de la información del ADN','Transportar los aminoácidos','Formar la membrana celular'],0],['¿Dónde se leen los codones?',['En la membrana','En el ribosoma','En los aminoácidos'],1],['¿Qué transporta el ARNt?',['Proteínas terminadas','ADN completo','Aminoácidos'],2]];
questions.forEach(([title,options],i)=>{const field=document.createElement('fieldset'),legend=document.createElement('legend');legend.textContent=title;field.append(legend);options.forEach((option,j)=>{const label=document.createElement('label'),input=document.createElement('input');input.type='radio';input.name='final-'+i;input.value=j;label.append(input,document.createTextNode(option));field.append(label);});$('final-questions').append(field);});
$('final-quiz').onsubmit=e=>{e.preventDefault();const answers=questions.map((q,i)=>document.querySelector('input[name="final-'+i+'"]:checked'));if(answers.some(a=>!a)){$('quiz-feedback').textContent='Responde las tres preguntas antes de ver tu resultado.';return;}const score=answers.filter((a,i)=>Number(a.value)===questions[i][2]).length;$('quiz-feedback').textContent=score+' de 3 respuestas correctas. '+(score===3?'¡Muy bien! Ya relacionas el mensaje, el ribosoma y el transporte de aminoácidos.':'Puedes volver a intentar. Recuerda: el ARNm lleva el mensaje; el ribosoma lee los codones; el ARNt transporta aminoácidos.');};
$('quiz-reset').onclick=()=>{$('final-quiz').reset();$('quiz-feedback').textContent='';};
})();
