/* Código estándar NCBI, tabla 1. Anticodones ideales sin wobble. */
(function(root){
'use strict';
const names={F:['Fenilalanina','Phe'],L:['Leucina','Leu'],S:['Serina','Ser'],Y:['Tirosina','Tyr'],'*':['STOP','STOP'],C:['Cisteína','Cys'],W:['Triptófano','Trp'],P:['Prolina','Pro'],H:['Histidina','His'],Q:['Glutamina','Gln'],R:['Arginina','Arg'],I:['Isoleucina','Ile'],M:['Metionina','Met'],T:['Treonina','Thr'],N:['Asparagina','Asn'],K:['Lisina','Lys'],V:['Valina','Val'],A:['Alanina','Ala'],D:['Ácido aspártico','Asp'],E:['Ácido glutámico','Glu'],G:['Glicina','Gly']};
const code={},letters='UCAG',aas='FFLLSSSSYY**CC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG';
let n=0;for(const a of letters)for(const b of letters)for(const c of letters){const symbol=aas[n++];code[a+b+c]={symbol,name:names[symbol][0],short:names[symbol][1]};}
function clean(s,type='RNA'){const v=String(s).replace(/\s/g,'').toUpperCase();if(!v)throw Error('Escribe una secuencia.');if(v.length>600)throw Error('Usa como máximo 600 nucleótidos.');if(!(type==='DNA'?/^[ATCG]+$/:/^[AUCG]+$/).test(v))throw Error(type==='DNA'?'ADN: usa únicamente A, T, C y G; se permiten espacios.':'ARNm: usa únicamente A, U, C y G; se permiten espacios.');return v;}
function transcribe(s,strand='coding'){s=clean(s,'DNA');if(!['coding','template'].includes(strand))throw Error('Selecciona una hebra válida.');return strand==='coding'?s.replace(/T/g,'U'):[...s].map(x=>({A:'U',T:'A',C:'G',G:'C'})[x]).join('');}
function anti(c){c=clean(c);if(c.length!==3)throw Error('Un codón debe tener tres bases.');if(code[c].symbol==='*')return null;return [...c].map(x=>({A:'U',U:'A',C:'G',G:'C'})[x]).join('');}
function translate(s){s=clean(s);const start=s.indexOf('AUG'),rows=[],chain=[];if(start<0)return {sequence:s,start,rows,chain,stop:false,tail:'',message:'No se encontró AUG: no se inicia la traducción en este modelo.'};let stop=false,i=start;for(;i+2<s.length;i+=3){const codon=s.slice(i,i+3),aa=code[codon];rows.push({codon,aa,index:i,anticodon:anti(codon)});if(aa.symbol==='*'){stop=true;break;}chain.push(aa.short);}return {sequence:s,start,rows,chain,stop,tail:stop?'':s.slice(i),message:stop?'Terminación por STOP.':'Fragmento sin STOP: cadena incompleta; no se simula liberación normal.'};}
function mutate(s,pos,base){s=clean(s);if(!Number.isInteger(pos)||pos<1||pos>s.length)throw Error('La posición debe ser un entero entre 1 y '+s.length+'.');if(!/^[AUCG]$/.test(base))throw Error('Selecciona una base A, U, C o G.');if(s[pos-1]===base)throw Error('Elige una base diferente de la original.');const changed=s.slice(0,pos-1)+base+s.slice(pos),normal=translate(s),mutated=translate(changed);let type,oldCodon='',newCodon='';const row=normal.rows.find(r=>pos-1>=r.index&&pos-1<r.index+3);if(!row)type='Fuera de la región traducida del modelo';else{oldCodon=row.codon;newCodon=changed.slice(row.index,row.index+3);const before=code[oldCodon],after=code[newCodon];if(row.index===normal.start&&newCodon!=='AUG')type='Pérdida del codón de inicio';else if(before.symbol==='*'&&after.symbol!=='*')type='Pérdida de STOP (stop-loss)';else if(before.symbol===after.symbol)type=before.symbol==='*'?'STOP conservado':'Silenciosa';else if(after.symbol==='*')type='Sin sentido (nonsense)';else type='Cambio de sentido (missense)';}return {original:s,changed,pos,base,normal,mutated,type,oldCodon,newCodon};}
function frames(s){const t=translate(s),states=[{phase:'Preparado',p:null,a:null,e:null,chain:[],index:0,message:t.message,done:false}];if(t.start<0)return [{...states[0],done:true}];let p=t.rows[0],chain=['Met'];states.push({phase:'Iniciación',p,a:null,e:null,chain:[...chain],index:p.index,message:'AUG fue reconocido. El ARNt iniciador con Metionina entra directamente en P.',done:false});for(const r of t.rows.slice(1)){if(r.aa.symbol==='*'){states.push({phase:'Terminación',p:null,a:null,e:null,release:r.codon,chain:[...chain],index:r.index,message:r.codon+' es STOP: actúa un factor de liberación, no un ARNt. Cadena liberada.',done:true});return states;}states.push({phase:'Reconocimiento',p,a:r,e:null,chain:[...chain],index:r.index,message:'Entra a A el ARNt con anticodón 3′-'+r.anticodon+'-5′ y '+r.aa.name+'.',done:false});chain.push(r.aa.short);states.push({phase:'Enlace peptídico',p:{...p,empty:true},a:{...r,carries:true},e:null,chain:[...chain],index:r.index,message:'Se forma un enlace peptídico; la cadena se transfiere del ARNt en P al de A.',done:false});states.push({phase:'Translocación',p:r,a:null,e:{...p,empty:true},chain:[...chain],index:r.index,message:'El ribosoma avanza tres nucleótidos: A → P, P → E. El ARNt descargado sale por E.',done:false});p=r;}states.push({phase:'Fragmento incompleto',p,a:null,e:null,chain:[...chain],index:p.index,message:t.message+(t.tail?' Quedan '+t.tail.length+' bases sin completar un codón.':''),done:true});return states;}
const api={code,clean,transcribe,anti,translate,mutate,frames};if(typeof module!=='undefined')module.exports=api;root.BioScience=api;
})(typeof globalThis!=='undefined'?globalThis:this);
