'use strict';
const S=BioScience,$=id=>document.getElementById(id);let states=[],step=0,snapshot='',mutation=null;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]);
function notice(id,text,error=false){$(id).textContent=text;$(id).classList.toggle('error',error);}
function guard(id,fn){try{fn();}catch(e){notice(id,e.message,true);}}
function bases(seq,pos=-1){return [...seq].map((b,i)=>'<span class="base '+b+(i===pos?' changed':'')+'"'+(i===pos?' title="Base sustituida, posición '+(i+1)+'"':'')+'>'+b+'</span>').join('');}
function chainHTML(chain){return chain.length?chain.map(x=>'<span class="aa">'+x+'</span>').join('<span aria-label="enlace peptídico">—</span>'):'Sin cadena';}
function reset(){states=[];step=0;snapshot='';$('next').disabled=true;$('start').disabled=false;$('phase').textContent='Preparado';for(const x of ['e','p','a'])$('site-'+x).innerHTML='';$('chain').textContent='—';$('codon-strip').innerHTML='';$('moving-rna').innerHTML='';$('progress').value=0;$('progress-number').textContent='0 %';$('progress-label').textContent='Listo para iniciar';$('chain-title').textContent='CADENA EN FORMACIÓN';notice('context','Inicia la traducción para reconocer AUG y colocar el primer ARNt en P.');}
function invalidate(){reset();mutation=null;$('comparison').innerHTML='';notice('mutation-status','');updateBase();}
function updateBase(){const s=$('rna').value.replace(/\s/g,'').toUpperCase();$('original-base').value=s[Number($('position').value)-1]||'—';$('position').max=s.length;}
function drawTRNA(r,site,frame){if(!r)return '';return '<div class="trna '+(r.empty?'empty':'')+'"><span class="amino">'+(r.empty?'Descargado':r.carries||site==='p'?'Cadena: '+frame.chain.length+' aa':r.aa.short)+'</span><span class="stem"></span><strong>ARNt · '+r.aa.short+'</strong><small>'+r.aa.name+'</small><span class="anti">3′-'+r.anticodon+'-5′</span><small>codón 5′-'+r.codon+'-3′</small></div>';}
function renderFrame(){const f=states[step];$('phase').textContent=f.phase;for(const x of ['e','p','a'])$('site-'+x).innerHTML=drawTRNA(f[x],x,f);if(f.release)$('site-a').innerHTML='<span class="release">Factor de<br>liberación<br>'+f.release+'</span>';$('chain').innerHTML=chainHTML(f.chain);notice('context',f.message);$('chain-title').textContent=f.release?'CADENA POLIPEPTÍDICA PRODUCIDA':f.done?'FRAGMENTO POLIPEPTÍDICO':'CADENA EN FORMACIÓN';$('next').disabled=f.done;const t=S.translate(snapshot),pct=states.length===1?0:Math.round(step/(states.length-1)*100);$('progress').value=pct;$('progress-number').textContent=pct+' %';$('progress-label').textContent='Paso '+step+' de '+(states.length-1);$('codon-strip').innerHTML=t.rows.map(r=>'<div class="codon '+(r.index===f.index?'reading':'')+'">'+bases(r.codon)+'<small>'+r.aa.short+'</small></div>').join('');const w=$('site-a').getBoundingClientRect().left-$('site-p').getBoundingClientRect().left;const pIndex=f.p?f.p.index:(f.release?f.index-3:f.index);const offset=t.start<0?0:(pIndex-t.start)/3;$('moving-rna').innerHTML=t.rows.map(r=>'<span class="mrna-codon" style="width:'+w+'px">'+r.codon+'</span>').join('');$('moving-rna').style.transform='translateX('+(-w/2-offset*w)+'px)';}
$('start').onclick=()=>guard('context',()=>{snapshot=S.clean($('rna').value);$('rna').value=snapshot.match(/.{1,3}/g).join(' ');states=S.frames(snapshot);step=states.length>1?1:0;$('start').disabled=true;renderFrame();});
$('next').onclick=()=>{if(step<states.length-1){step++;renderFrame();}};$('reset').onclick=reset;
$('transcribe').onclick=()=>guard('dna-status',()=>{const r=S.transcribe($('dna').value,$('strand').value);$('dna').value=S.clean($('dna').value,'DNA');$('rna').value=r.match(/.{1,3}/g).join(' ');invalidate();notice('dna-status','✓ Transcripción correcta. ARNm sintetizado 5′ → 3′.');});
$('example').onclick=()=>{$('dna').value=$('strand').value==='coding'?'ATG AAA GCT TTT TAA':'TAC TTT CGA AAA ATT';$('transcribe').click();$('position').value=4;$('new-base').value='C';updateBase();};
$('strand').onchange=()=>{$('strand-help').textContent=$('strand').value==='coding'?'La hebra codificante 5′ → 3′ coincide con el ARNm, sustituyendo T por U.':'La hebra molde se introduce 3′ → 5′; se aplica complementariedad para sintetizar ARNm 5′ → 3′.';notice('dna-status','Hebra cambiada. Verifica tu ADN o carga el ejemplo correspondiente.');};
$('rna').oninput=invalidate;$('position').oninput=()=>{updateBase();clearMutation();};$('new-base').onchange=clearMutation;
function clearMutation(){mutation=null;$('comparison').innerHTML='';notice('mutation-status','');}
function comparison(){const m=mutation;if(!m)return;function card(title,t,seq){return '<div class="compare-card"><p class="eyebrow">'+title+'</p><div class="sequence">5′ '+bases(seq,m.pos-1)+' 3′</div><div class="codon-strip">'+t.rows.map(r=>'<div class="codon '+(m.pos-1>=r.index&&m.pos-1<r.index+3?'changed':'')+'">'+r.codon+'<small>'+r.aa.name+'</small></div>').join('')+'</div><div class="chain">'+chainHTML(t.chain)+'</div><p class="hint">'+t.message+'</p></div>';}$('comparison').innerHTML=card('SECUENCIA NORMAL',m.normal,m.original)+card('SECUENCIA MUTADA',m.mutated,m.changed)+'<div class="conclusion"><strong>'+m.type+'</strong><p>'+(m.oldCodon?m.oldCodon+' → '+S.code[m.oldCodon].name+'; '+m.newCodon+' → '+S.code[m.newCodon].name+'. ':'')+'Una sustitución de una sola base puede modificar un aminoácido de la cadena polipeptídica.</p><p>No todas las mutaciones producen necesariamente una enfermedad; su efecto depende del lugar y consecuencia molecular de la alteración.</p></div>';}
function createMutation(){clearMutation();guard('mutation-status',()=>{mutation=S.mutate($('rna').value,Number($('position').value),$('new-base').value);notice('mutation-status','✓ Base '+mutation.pos+': '+mutation.original[mutation.pos-1]+' → '+mutation.base+'. La base modificada está enmarcada.');comparison();});}
$('mutate').onclick=createMutation;$('compare').onclick=createMutation;
const challenges=[{q:'1. ADN codificante 5′-ATGAAAGCT-3′. ¿Cuál es su ARNm 5′ → 3′?',options:['UACUUUCGA','AUGAAAGCU','ATGAAAGCT','AUGUUUGCU'],answer:1,why:'La hebra codificante coincide con el ARNm salvo T → U: AUGAAAGCU.'},{q:'2. Divide 5′-AUGAAAGCUUUUUAA-3′ en codones desde AUG.',options:['AUG | AAA | GCU | UUU | UAA','AU | GAAA | GCU | UUUUAA','AUG | AA | AGC | UUU | UUAA','AUG | AAA | GCUU | UU | UAA'],answer:0,why:'Cada codón tiene tres bases: AUG | AAA | GCU | UUU | UAA.'},{q:'3. Elige el ARNt para el codón 5′-AAA-3′. Anticodones escritos 3′ → 5′.',options:['GCG','AAA','CUU','UUU'],answer:3,why:'A se aparea con U. El anticodón es 3′-UUU-5′ y este ARNt lleva Lisina.'},{q:'4. ¿Qué aminoácido especifica el codón 5′-GCU-3′?',options:['Glutamina','Lisina','Alanina','STOP'],answer:2,why:'GCU codifica Alanina (Ala) en el código genético estándar.'},{q:'5. En AUG AAA GCU UUU UAA, la base 4 cambia A → C. ¿Qué sucede?',options:['Silenciosa: conserva Lisina','Missense: Lisina → Glutamina','Nonsense: aparece STOP','No hay sustitución'],answer:1,why:'AAA codifica Lisina; CAA codifica Glutamina. Es cambio de sentido (missense).'}];
let qi=0,results=[];function drawQuestion(){const q=challenges[qi];$('challenge-number').textContent='DESAFÍO '+(qi+1)+' DE 5';$('question').textContent=q.q;$('answers').innerHTML=q.options.map((o,i)=>'<label class="answer"><input type="radio" name="answer" value="'+i+'">'+esc(o)+'</label>').join('');$('check').disabled=false;$('new-challenge').disabled=true;notice('challenge-feedback','');$('challenge-summary').textContent='';}
$('check').onclick=()=>{const a=document.querySelector('input[name="answer"]:checked');if(!a){notice('challenge-feedback','Selecciona una respuesta antes de comprobar.',true);return;}const correct=Number(a.value)===challenges[qi].answer;results.push({correct,question:qi});notice('challenge-feedback',(correct?'✓ Correcto. ':'✗ Revisa el razonamiento. ')+challenges[qi].why,!correct);$('check').disabled=true;document.querySelectorAll('input[name="answer"]').forEach(x=>x.disabled=true);$('new-challenge').disabled=false;const hits=results.filter(x=>x.correct).length;$('score').textContent=hits+' / 5 aciertos';if(qi===4){$('challenge-summary').textContent='Resultado final: '+(hits*20)+' / 100 puntos · '+hits+' aciertos · '+(5-hits)+' errores. Revisa las explicaciones y vuelve a intentarlo.';$('new-challenge').textContent='Reiniciar desafíos';}};
$('new-challenge').onclick=()=>{if(qi===4){qi=0;results=[];$('score').textContent='0 / 5 aciertos';$('new-challenge').textContent='Nuevo desafío →';}else qi++;drawQuestion();};
$('genetic-code').innerHTML=Object.entries(S.code).map(([c,a])=>'<tr><td>'+c+'</td><td>'+a.name+'</td><td>'+a.short+'</td><td>'+(S.anti(c)||'No hay ARNt: factor de liberación')+'</td></tr>').join('');
document.querySelectorAll('nav a').forEach(a=>a.onclick=()=>{document.querySelectorAll('nav a').forEach(x=>x.classList.remove('active'));a.classList.add('active');});
addEventListener('resize',()=>{if(states.length)renderFrame();});drawQuestion();updateBase();

// Puente opcional: comparte el mismo estado visible sin depender de su disponibilidad.
if(document.modelContext?.registerTool){
 const lifecycle=new AbortController();
 const tool={name:'biocode_transcribe_dna',title:'Transcribir ADN en BioCode',description:'Valida ADN, actualiza el ARNm visible y reinicia la simulación.',inputSchema:{type:'object',properties:{dna:{type:'string'},strand:{type:'string',enum:['coding','template']}},required:['dna','strand'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input.dna!=='string')throw Error('Falta ADN válido.');const rna=S.transcribe(input.dna,input.strand);$('strand').value=input.strand;$('strand').onchange();$('dna').value=input.dna;$('transcribe').click();return {rna,orientation:'5′ → 3′'};}};
 try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{/* La interfaz sigue disponible si el navegador no admite el puente. */}
 addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}
