/* Pruebas de desarrollo: npm install --no-save playwright, o NODE_PATH al paquete disponible. */
const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const {pathToFileURL}=require('node:url');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});const check=(name,value)=>{assert.ok(value,name);checks.push({name,status:'PASS'});};const root=path.resolve(__dirname,'..');
try{await page.goto(pathToFileURL(path.join(root,'index.html')).href);check('Carga de aplicación',await page.title()==='BioCode · Laboratorio de síntesis proteica');check('64 filas de código',await page.locator('#genetic-code tr').count()===64);
await page.locator('#example').click();check('Cargar ejemplo y transcribir',(await page.locator('#rna').inputValue()).replace(/\s/g,'')==='AUGAAAGCUUUUUAA');
await page.locator('#strand').selectOption('template');await page.locator('#example').click();check('Molde correcto',(await page.locator('#dna').inputValue())==='TACTTTCGAAAAATT');
await page.locator('#dna').fill('atg x');await page.locator('#transcribe').click();check('Mensaje de ADN inválido',(await page.locator('#dna-status').textContent()).includes('únicamente'));await page.locator('#strand').selectOption('coding');await page.locator('#example').click();
await page.locator('#start').click();check('Iniciación en P',(await page.locator('#site-p').textContent()).includes('UAC'));await page.locator('#next').click();check('ARNt entrante en A',(await page.locator('#site-a').textContent()).includes('UUU'));await page.locator('#next').click();check('Transferencia de cadena',(await page.locator('#site-p').textContent()).includes('Descargado'));await page.locator('#next').click();check('Translocación y E',(await page.locator('#site-e').textContent()).includes('Descargado'));await page.emulateMedia({reducedMotion:'reduce'}); await page.waitForTimeout(500); await page.screenshot({path:path.join(root,'assets/images/desktop.png'),fullPage:false});
let steps=0;while(await page.locator('#next').isEnabled()&&steps++<100)await page.locator('#next').click();check('Terminación',(await page.locator('#phase').textContent())==='Terminación');check('Cadena normal',JSON.stringify(await page.locator('#chain .aa').allTextContents())===JSON.stringify(['Met','Lys','Ala','Phe']));check('STOP usa factor',(await page.locator('#site-a').textContent()).includes('Factor'));check('100 %',(await page.locator('#progress').getAttribute('value'))==='100');
await page.locator('#mutate').click();check('Missense calculado',(await page.locator('#comparison').textContent()).includes('Cambio de sentido (missense)'));check('Cambio Lys/Gln',JSON.stringify(await page.locator('.compare-card').nth(1).locator('.aa').allTextContents())===JSON.stringify(['Met','Gln','Ala','Phe']));
await page.locator('#position').fill('6');await page.locator('#new-base').selectOption('G');await page.locator('#compare').click();check('Silenciosa en interfaz',(await page.locator('#comparison').textContent()).includes('Silenciosa'));
await page.locator('#position').fill('4');await page.locator('#new-base').selectOption('U');await page.locator('#compare').click();check('Nonsense en interfaz',(await page.locator('#comparison').textContent()).includes('nonsense'));await page.locator('#position').fill('0');await page.locator('#compare').click();check('Posición inválida',(await page.locator('#mutation-status').textContent()).includes('entero'));await page.locator('#position').fill('4');await page.locator('#new-base').selectOption('A');await page.locator('#compare').click();check('Sin sustitución rechazado',(await page.locator('#mutation-status').textContent()).includes('diferente'));
await page.locator('#rna').fill('AUGX');await page.locator('#start').click();check('ARN inválido',(await page.locator('#context').textContent()).includes('únicamente'));await page.locator('#rna').fill('AAAGCU');await page.locator('#start').click();check('Sin inicio',(await page.locator('#context').textContent()).includes('No se encontró AUG'));await page.locator('#rna').fill('AUG AAA G');await page.locator('#start').click();while(await page.locator('#next').isEnabled())await page.locator('#next').click();check('Sin STOP ni liberación',(await page.locator('#context').textContent()).includes('sin STOP')&&!(await page.locator('#site-a').textContent()).includes('Factor'));
await page.locator('#reset').click();check('Reinicio',await page.locator('#next').isDisabled()&&(await page.locator('#chain').textContent())==='—');
check('Desafío oculta solución',(await page.locator('#challenge-feedback').textContent())==='');await page.locator('#check').click();check('Desafío exige selección',(await page.locator('#challenge-feedback').textContent()).includes('Selecciona'));const answers=[0,0,3,2,1];for(let i=0;i<5;i++){await page.locator('input[name=answer]').nth(answers[i]).check();await page.locator('#check').click();check('Respuesta '+(i+1)+' bloqueada tras comprobar',await page.locator('#check').isDisabled());if(i<4)await page.locator('#new-challenge').click();}check('Puntaje, aciertos y errores',(await page.locator('#challenge-summary').textContent()).includes('80 / 100 puntos · 4 aciertos · 1 errores'));await page.locator('#new-challenge').click();check('Reinicio desafío',(await page.locator('#score').textContent())==='0 / 5 aciertos');
await page.goto(pathToFileURL(path.join(root,'docs/interno.html')).href);await page.locator('#test-total').fill('10');await page.locator('#test-pass').fill('8');await page.locator('#save-validation').click();check('Precisión calculada',(await page.locator('#validation-result').textContent()).includes('80.0 %'));await page.locator('#test-pass').fill('11');await page.locator('#save-validation').click();check('Validación no permite más correctas que total',(await page.locator('#validation-result').textContent()).includes('no puede superar'));await page.locator('#improvements').fill('PRUEBA AUTOMÁTICA TEMPORAL');await page.locator('#save-improvements').click();await page.reload();check('Persistencia de registros',(await page.locator('#improvements').inputValue())==='PRUEBA AUTOMÁTICA TEMPORAL'&&(await page.locator('#test-pass').inputValue())==='8');await page.evaluate(()=>localStorage.clear());await page.goto(pathToFileURL(path.join(root,'index.html')).href);
const links=await page.locator('a[href]').evaluateAll(as=>as.map(a=>a.getAttribute('href')));for(const href of links){if(href.startsWith('#'))check('Ancla '+href,await page.locator(href).count()===1);else if(!href.startsWith('http'))check('Archivo enlazado '+href,fs.existsSync(path.join(root,href)));}
for(const width of [1440,1024,768,390,320]){await page.setViewportSize({width,height:900});check('Sin desborde horizontal a '+width,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}await page.setViewportSize({width:390,height:844});await page.locator('#example').click();await page.locator('#start').click();await page.locator('#next').click();check('Traducción en móvil',(await page.locator('#site-a').textContent()).includes('UUU'));await page.locator('#new-base').selectOption('C');await page.locator('#mutate').click();check('Mutación en móvil',(await page.locator('#comparison').textContent()).includes('missense'));await page.locator('#inicio').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(root,'assets/images/mobile.png'),fullPage:true});
check('Sin errores de consola',errors.length===0);fs.writeFileSync(path.join(__dirname,'browser-results.json'),JSON.stringify({date:new Date().toISOString(),checks,errors},null,2));console.log(checks.length+' pruebas de navegador PASS; consola sin errores.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
