const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const crypto=require('node:crypto');const {pathToFileURL}=require('node:url');
(async()=>{const root=path.resolve(__dirname,'..'),out=path.join(root,'assets/images');const checks=[],errors=[];const test=(name,value)=>{assert.ok(value,name);checks.push({name,status:'PASS'});};
test('Motor científico sin cambios',crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'science.js'))).digest('hex')==='e663919a9afd39b9a12349bd730f1e1ff12b343b00a96b3feed e51bd3a8d1746'.replace(' ',''));
const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1100,height:1000},reducedMotion:'reduce'});page.on('pageerror',e=>errors.push(e.message));
try{const pages=['proyecto','pruebas','modelo-fisico','sesiones-47-54','cartilla-salud','cuaderno-campo','plano-prototipo','validacion-real','manual'];for(const name of pages){await page.goto(pathToFileURL(path.join(root,'docs',name+'.html')).href);test(name+': título y contenido',await page.locator('h1').count()>0&&(await page.locator('main').textContent()).length>400);const links=await page.locator('a[href]').evaluateAll(es=>es.map(e=>e.getAttribute('href')));for(const href of links.filter(h=>!h.startsWith('http')&&!h.startsWith('#'))){test(name+': enlace '+href,fs.existsSync(path.resolve(root,'docs',href.split('#')[0])));test(name+': enlace HTML',!href.endsWith('.md'));}await page.setViewportSize({width:390,height:844});test(name+': sin desborde móvil',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.setViewportSize({width:1100,height:1000});}
await page.goto(pathToFileURL(path.join(root,'docs/validacion-real.html')).href);test('Cuatro ensayos previstos',await page.locator('#trial-rows tr').count()===4);test('Observaciones y evaluaciones inicialmente vacías',await page.locator('#trial-rows tr').evaluateAll(rows=>rows.every(r=>[...r.querySelectorAll('[data-record]')].slice(2).every(el=>el.value===''))));
await page.getByRole('button',{name:'Añadir ensayo'}).click();test('Añadir quinta cadena',await page.locator('#trial-rows tr').count()===5);await page.getByLabel('Ensayo 5: entrada',{exact:true}).fill('AUG GGU UAA');await page.getByLabel('Ensayo 5: predicción',{exact:true}).fill('Met–Gly');await page.getByLabel('Ensayo 5: resultado observado',{exact:true}).fill('REGISTRO AUTOMÁTICO DE QA, NO ESCOLAR');await page.getByLabel('Ensayo 5: correcto/incorrecto',{exact:true}).selectOption('Correcto');await page.getByLabel('Fecha y responsables').fill('QA automática temporal');await page.getByRole('button',{name:'Guardar registro local'}).click();await page.reload();test('Persisten filas y observaciones propias',(await page.getByLabel('Ensayo 5: resultado observado',{exact:true}).inputValue())==='REGISTRO AUTOMÁTICO DE QA, NO ESCOLAR');test('No completa otras observaciones',(await page.getByLabel('Ensayo 1: resultado observado',{exact:true}).inputValue())==='');await page.emulateMedia({media:'print'});test('Impresión conserva texto introducido',(await page.getByLabel('Ensayo 5: resultado observado',{exact:true}).evaluate(e=>e.nextElementSibling.textContent))==='REGISTRO AUTOMÁTICO DE QA, NO ESCOLAR');await page.emulateMedia({media:'screen'});await page.evaluate(()=>localStorage.removeItem('biocode-real-trials-v1'));await page.reload();
await page.goto(pathToFileURL(path.join(root,'docs/sesiones-47-54.html')).href);const content=await page.locator('main').textContent();for(let i=47;i<=54;i++)test('Sesión '+i+' presente',content.includes('SESIÓN '+i+':'));for(let i=1;i<=10;i++)test('Paso '+i+' presente',content.includes('PASO '+i+':'));test('Pregunta exacta ARN polimerasa',content.includes("¿Cómo actúa la ARN polimerasa leyendo la hebra molde (3' a 5') y formando el ARNm maduro que sale del núcleo?"));test('Pregunta exacta mutación',content.includes('¿Qué ocurre si la base 4 cambia de Adenina a Citosina? (Mutación de cambio de sentido o silenciosa).'));test('Fotografías señaladas pendientes',content.includes('Pendiente de ejecución por Santiago y Joseph.'));
for(const [name,width]of [['cartilla-salud',688],['cuaderno-campo',1031],['plano-prototipo',688]]){await page.goto(pathToFileURL(path.join(root,'docs',name+'.html')).href);await page.emulateMedia({media:'print'});await page.setViewportSize({width,height:1050});test(name+': botón oculto al imprimir',!await page.locator('[data-print]').isVisible());const sizes=await page.locator('.page').evaluateAll(es=>es.map(e=>Math.ceil(e.getBoundingClientRect().height)));const max=name==='cuaderno-campo'?695:1015;test(name+': páginas dentro del área A4 ('+sizes.join(',')+' px)',sizes.every(h=>h<=max));await page.screenshot({path:path.join(out,name+'-print.png'),fullPage:true});await page.emulateMedia({media:'screen'});}
await page.goto(pathToFileURL(path.join(root,'docs/cuaderno-campo.html')).href);test('21 filas de campo',await page.locator('tbody tr').count()===21);test('Campos de campo vacíos',(await page.locator('tbody').allTextContents()).every(t=>!t.trim()));
await page.goto(pathToFileURL(path.join(root,'index.html')).href);test('Documentación retirada de interfaz pública',await page.locator('#documentacion, #validacion, #prototipo, a[href^="docs/"]').count()===0);test('Seis opciones de navegación',await page.locator('nav a').count()===6);test('Acerca de con autoría', (await page.locator('#acerca').textContent()).includes('Santiago Rivas · Joseph Valderrama'));test('Sin contenido administrativo público', !/rúbrica|cuaderno de campo|guion de exposición|cronograma|presupuesto|documentación|evidencias/i.test(await page.locator('body').innerText()));test('Sin enlaces principales a Markdown',(await page.locator('a[href$=".md"]').count())===0);const md=fs.readFileSync(path.join(root,'docs/proyecto.md'),'utf8');const summary=md.split('## Resumen final')[1].trim();test('Resumen informe <=250 palabras',summary.split(/\s+/).length<=250);const sessions=fs.readFileSync(path.join(root,'docs/sesiones-47-54.md'),'utf8');const p=sessions.split('BioCode responde a la necesidad')[1].split('## Referencias')[0];test('Resumen guía <=250 palabras',('BioCode responde a la necesidad'+p).trim().split(/\s+/).length<=250);test('Sin errores JS',errors.length===0);
fs.writeFileSync(path.join(__dirname,'docs-results.json'),JSON.stringify({date:new Date().toISOString(),checks,errors},null,2));console.log(checks.length+' comprobaciones documentales PASS');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
