const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const {pathToFileURL}=require('node:url');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'});const root=path.resolve(__dirname,'..'),checks=[];const test=(name,ok)=>{assert.ok(ok,name);checks.push({name,status:'PASS'});};try{
await page.goto(pathToFileURL(path.join(root,'index.html')).href);await page.locator('#start').click();await page.locator('#next').click();await page.locator('#next').click();await page.locator('#next').click();await page.locator('.ribosome-panel').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(root,'assets/images/mobile-ribosome.png')});
test('Codón AAA centrado en P a 390 px',await page.evaluate(()=>{const p=document.querySelector('#site-p').getBoundingClientRect(),c=document.querySelectorAll('.mrna-codon')[1].getBoundingClientRect();return Math.abs((p.left+p.width/2)-(c.left+c.width/2))<2;}));
await page.locator('#mutate').click();await page.locator('#position').fill('5');test('Cambiar posición borra comparación obsoleta',(await page.locator('#comparison').textContent())==='');
await page.locator('#rna').fill('AUG'+'AAA'.repeat(198)+'UAA');await page.locator('#start').click();for(let i=0;i<15;i++)await page.locator('#next').click();test('Secuencia de 600 bases sin desborde',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.setViewportSize({width:720,height:500});test('Reflujo equivalente a zoom 200 % en pantalla 1440',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.locator('#example').click();await page.locator('#reset').focus();await page.keyboard.press('Enter');test('Reiniciar por teclado',(await page.locator('#phase').textContent())==='Preparado');
await page.goto(pathToFileURL(path.join(root,'docs/recortables.html')).href);await page.evaluate(()=>{window.print=()=>{document.body.dataset.printed='yes';};});await page.getByRole('button',{name:'Imprimir recortables'}).click();test('Botón imprimir invoca impresión',await page.locator('body').getAttribute('data-printed')==='yes');await page.emulateMedia({media:'print'});test('Recortables mantienen medida 7 cm',await page.locator('.codon').first().evaluate(el=>Math.abs(el.getBoundingClientRect().width-7*96/2.54)<1));test('Controles ocultos al imprimir',await page.locator('.controls').evaluate(el=>getComputedStyle(el).display==='none'));await page.setViewportSize({width:900,height:1100});await page.screenshot({path:path.join(root,'assets/images/recortables-preview.png'),fullPage:false});
fs.writeFileSync(path.join(__dirname,'extended-results.json'),JSON.stringify({date:new Date().toISOString(),checks},null,2));console.log(checks.length+' comprobaciones adicionales PASS');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
