const assert=require('node:assert/strict');
const fs=require('node:fs');const path=require('node:path');const S=require('../science.js');
const report=[];function test(name,input,expected,fn){let actual;try{actual=fn();assert.deepEqual(actual,expected);report.push({name,input,expected,actual,status:'PASS'});}catch(e){report.push({name,input,expected,actual:String(actual??e.message),status:'FAIL'});}}
test('01 Cadena normal','AUG AAA GCU UUU UAA',['Met','Lys','Ala','Phe'],()=>S.translate('AUG AAA GCU UUU UAA').chain);
test('02 Mutación obligatoria','Base 4 A→C',['AUGCAAGCUUUUUAA',['Met','Gln','Ala','Phe'],'Cambio de sentido (missense)'],()=>{const m=S.mutate('AUGAAAGCUUUUUAA',4,'C');return [m.changed,m.mutated.chain,m.type];});
test('03 Anticodón orientado','5′-AUG-3′','UAC',()=>S.anti('AUG'));
test('04 STOP no aminoácido ni ARNt','AUGUAAAAA',[['Met'],true,null],()=>{const t=S.translate('AUGUAAAAA');return [t.chain,t.stop,S.anti('UAA')];});
test('05 Rechazo de caracteres','AUGXAA',true,()=>{assert.throws(()=>S.clean('AUGXAA'),/únicamente/);return true;});
test('06 Espacios',' aug aaa gcu ',['Met','Lys','Ala'],()=>S.translate(' aug aaa gcu ').chain);
test('07 Silenciosa generada','Buscar sustitución sin cambio aminoácido','Silenciosa',()=>{for(let p=4;p<=12;p++)for(const b of 'AUCG'){if(b==='AUGAAAGCUUUUUAA'[p-1])continue;const m=S.mutate('AUGAAAGCUUUUUAA',p,b);if(m.type==='Silenciosa'){fs.writeFileSync(path.join(__dirname,'silent-example.json'),JSON.stringify(m,null,2));return m.type;}}});
test('08 Nonsense generado','Buscar sustitución a STOP','Sin sentido (nonsense)',()=>{for(let p=4;p<=12;p++)for(const b of 'AUCG'){if(b==='AUGAAAGCUUUUUAA'[p-1])continue;const m=S.mutate('AUGAAAGCUUUUUAA',p,b);if(m.type.includes('nonsense')){fs.writeFileSync(path.join(__dirname,'nonsense-example.json'),JSON.stringify(m,null,2));return m.type;}}});
test('09 Hebra codificante','5′-ATGAAAGCTTTTTAA-3′','AUGAAAGCUUUUUAA',()=>S.transcribe('ATGAAAGCTTTTTAA'));
test('10 Hebra molde con espacios','3′-TACTTTCGAAA AATT-5′','AUGAAAGCUUUUUAA',()=>S.transcribe('TACTTTCGAAA AATT','template'));
test('11 Tabla completa','64 tripletes',[64,61,3],()=>[Object.keys(S.code).length,Object.values(S.code).filter(a=>a.symbol!=='*').length,Object.values(S.code).filter(a=>a.symbol==='*').length]);
test('12 Todos los codones frente a fixture independiente','20 familias y STOP',true,()=>{const groups={Phe:'UUU UUC',Leu:'UUA UUG CUU CUC CUA CUG',Ile:'AUU AUC AUA',Met:'AUG',Val:'GUU GUC GUA GUG',Ser:'UCU UCC UCA UCG AGU AGC',Pro:'CCU CCC CCA CCG',Thr:'ACU ACC ACA ACG',Ala:'GCU GCC GCA GCG',Tyr:'UAU UAC',His:'CAU CAC',Gln:'CAA CAG',Asn:'AAU AAC',Lys:'AAA AAG',Asp:'GAU GAC',Glu:'GAA GAG',Cys:'UGU UGC',Trp:'UGG',Arg:'CGU CGC CGA CGG AGA AGG',Gly:'GGU GGC GGA GGG',STOP:'UAA UAG UGA'};for(const [aa,codons]of Object.entries(groups))for(const c of codons.split(' '))assert.equal(S.code[c].short,aa);return true;});
test('13 Los tres STOP','UAA UAG UGA',true,()=>{for(const c of ['UAA','UAG','UGA']){assert.deepEqual(S.translate('AUG'+c+'AAA').chain,['Met']);assert.equal(S.anti(c),null);}return true;});
test('14 Sin AUG','AAAGCU',[false,0],()=>{const t=S.translate('AAAGCU');return [t.stop,t.chain.length];});
test('15 Marco desde primer AUG','CCAUGAAAUAA',[2,['Met','Lys']],()=>{const t=S.translate('CCAUGAAAUAA');return [t.start,t.chain];});
test('16 Fragmento sin STOP','AUGAAAG',[false,'G'],()=>{const t=S.translate('AUGAAAG');return [t.stop,t.tail];});
test('17 Pérdida de inicio','AUGAAA, base 1→C','Pérdida del codón de inicio',()=>S.mutate('AUGAAA',1,'C').type);
test('18 Pérdida de STOP','AUGUAA, base 4→C','Pérdida de STOP (stop-loss)',()=>S.mutate('AUGUAA',4,'C').type);
test('19 Posición después de STOP','AUGUAAAAA, base 7→C','Fuera de la región traducida del modelo',()=>S.mutate('AUGUAAAAA',7,'C').type);
test('20 Validación posición y base','0, 1.5, 999, sin cambio',true,()=>{for(const p of [0,1.5,999])assert.throws(()=>S.mutate('AUGAAA',p,'C'));assert.throws(()=>S.mutate('AUGAAA',4,'A'));assert.throws(()=>S.mutate('AUGAAA',4,'T'));return true;});
test('21 Estados P/A/E y enlace','AUGAAAUAA',true,()=>{const f=S.frames('AUGAAAUAA');assert.equal(f[1].p.codon,'AUG');assert.equal(f[1].a,null);assert.equal(f[2].a.codon,'AAA');assert.equal(f[3].p.empty,true);assert.equal(f[3].a.carries,true);assert.equal(f[4].p.codon,'AAA');assert.equal(f[4].e.empty,true);assert.equal(f[5].release,'UAA');assert.equal(f[5].a,null);return true;});
test('22 Anticodones de todos los codones','Complementariedad A-U y C-G',true,()=>{for(const [c,a]of Object.entries(S.code)){if(a.symbol==='*')continue;const anti=S.anti(c);for(let i=0;i<3;i++)assert.equal(anti[i],{A:'U',U:'A',C:'G',G:'C'}[c[i]]);}return true;});
test('23 Vacío, T en ARN, U en ADN y límite','Entradas inválidas',true,()=>{for(const s of ['','ATG','A'.repeat(601)])assert.throws(()=>S.clean(s));assert.throws(()=>S.transcribe('AUG'));return true;});
test('24 Marco no múltiplo de tres en mutación','CCAUGAAAUAA, base 6→C','Cambio de sentido (missense)',()=>S.mutate('CCAUGAAAUAA',6,'C').type);
test('25 STOP fuera de marco no termina','AUGCUAAGCUAA',['Met','Leu','Ser'],()=>S.translate('AUGCUAAGCUAA').chain);
test('26 Fragmento no se libera','AUGAAA',true,()=>{const f=S.frames('AUGAAA').at(-1);return f.done&&!f.release&&!!f.p;});
fs.writeFileSync(path.join(__dirname,'science-results.json'),JSON.stringify({date:new Date().toISOString(),tests:report},null,2));
for(const r of report)console.log(r.status,r.name);console.log(report.filter(x=>x.status==='PASS').length+'/'+report.length);if(report.some(x=>x.status==='FAIL'))process.exitCode=1;
